### ISSUE TITLE
Total time

### ISSUE THREAD

**Issue by pnevyk** [jzbor/foliot#2]
First of all, thanks for the tool! It really works perfectly for my use case.

I use the comment argument of the `clockout` command as the name of the task I was working on. And I want to know how much time I spent on specific task in total. You already added `--filter` option, which is great. Now I would like to see the sum of the times of individual entries, taking `--filter` value (if provided) into account, either in `summarize` or `show` views.

I don't have any preference how the total time is displayed. But when I think about, the most natural way would be imho to add another row into `summarize` table with totals, something like this:

```
 ╭───────────────────┬─────────────┬──────────────┬──────┬─────────╮
 │ month             │ total hours │ hours / week │ days │ entries │
 ├───────────────────┼─────────────┼──────────────┼──────┼─────────┤
 │ 2023/09 September │   01:41h    │     0.57     │  2   │    2    │
 │ 2023/10 October   │   03:23h    │     1.27     │  4   │    5    │
 ├───────────────────┼─────────────┼──────────────┼──────┼─────────┤
 │ total             │   05:04h    │              │  6   │    7    │
 ╰───────────────────┴─────────────┴──────────────┴──────┴─────────╯
```

I am just not sure what to put into hours / week column.

Anyway, feel free to come up with your own solution.

**Comment by jzbor** [comment]
Hi,
Thanks for the feedback. I think this is a good idea, so I made a quick dirty draft to implement this. The result looks like this:
```
                                                                 
 ╭───────────────┬─────────────┬──────────────┬──────┬─────────╮ 
 │ month         │ total hours │ hours / week │ days │ entries │ 
 ├───────────────┼─────────────┼──────────────┼──────┼─────────┤ 
 │ 2023/03 March │   01:30h    │     0.68     │  2   │    2    │ 
 │ 2023/04 April │   02:00h    │     0.47     │  1   │    1    │ 
 │ Total         │   03:30h    │      -       │  3   │    3    │ 
 ╰───────────────┴─────────────┴──────────────┴──────┴─────────╯ 
                                                                 
```

If you want to try it out ahead of time this patch should enable the desired behavior:
```diff
diff --git a/src/main.rs b/src/main.rs
index a13173c..321a450 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -689,6 +689,16 @@ fn summarize(filter: &Option<String>, tail: usize, args: &Args) -> Result<(), St
         .collect();
     table_items.sort();
 
+    let total = SummaryTableItem {
+        month: "Total".to_owned(),
+        total_hours: table_items.iter().map(|i| i.total_hours)
+            .fold(HumanDuration { hours: 0, minutes: 0 }, |a, b| a + b),
+        hours_per_week: "-".to_owned(),
+        days: table_items.iter().map(|i| i.days).sum(),
+        nitems: table_items.iter().map(|i| i.nitems).sum(),
+    };
+    table_items.push(total);
+
     let items_slice = if tail == 0 {
         table_items.as_slice()
     } else {
```
I will probably push this to main in a few days...
Greetings :)

**Comment by pnevyk** [comment]
Thanks. I don't need this urgently, so I can definitely wait for a new release which can be anytime you decide.

**Comment by jzbor** [comment]
Sorry for taking so long. Kinda forgot about it, but now the implementation is finally available on main.

**Comment by jzbor** [comment]
Also published a new version
